export const TACTICAL_KEYWORDS: Record<string, string[]> = {
  block: [
    "bloque",
    "bloque medio",
    "equipo corto",
    "equipo largo",
    "hundirse",
    "achicar",
    "altura del bloque",
    "repliegue",
    "lineas",
  ],
  "high-block": [
    "bloque alto",
    "presion alta",
    "altura alta",
    "equipo arriba",
    "salto alto",
    "subir el bloque",
    "subimos el bloque",
    "linea alta",
  ],
  "low-block": [
    "bloque bajo",
    "repliegue bajo",
    "muy atras",
    "metidos atras",
    "defender cerca del area",
  ],
  strikers: [
    "delanteros",
    "punta",
    "puntas",
    "9",
    "primer defensor",
    "presionar arriba",
    "retroceden los puntas",
  ],
  midfield: [
    "mediocampo",
    "volantes",
    "doble 5",
    "segunda linea",
    "internos",
    "pivot",
    "mediocentros",
  ],
  compactness: [
    "compacto",
    "compacidad",
    "equipo corto",
    "partido",
    "juntos",
    "entre lineas",
    "distancias",
  ],
  spacing: [
    "espacios",
    "separacion",
    "distancias",
    "escalonados",
    "apoyos",
    "cercanias",
  ],
  width: [
    "ancho",
    "amplitud",
    "abrir la cancha",
    "muy ancho",
    "cerrarse demasiado",
  ],
  depth: [
    "profundidad",
    "altura",
    "espalda de la defensa",
    "equipo largo",
    "mucha distancia",
  ],
  interior: [
    "interior",
    "carril interior",
    "pasillo interior",
    "medio espacio",
    "half space",
  ],
  "build-up": [
    "salida",
    "salir jugando",
    "construccion",
    "primer pase",
    "inicio de jugada",
    "salida limpia",
    "salir limpio",
    "salir por abajo",
    "nos aprietan en salida",
    "lo aprietan al 5",
    "5 lo aprietan",
    "cinco lo aprietan",
    "recibe de espaldas",
    "recibir de espaldas",
  ],
  buildUp: [
    "salida",
    "salir jugando",
    "construccion",
    "primer pase",
    "inicio de jugada",
    "salida limpia",
  ],
  "building-up": [
    "salida",
    "salir jugando",
    "construccion",
    "primer pase",
    "inicio de jugada",
    "salida limpia",
  ],
  pressing: [
    "presion",
    "presionar",
    "saltar",
    "gatillo",
    "cazar",
    "activar presion",
    "ir a apretar",
    "apretar",
    "aprieta",
    "aprietan",
    "apretando",
    "nos aprietan",
    "lo aprietan",
  ],
  "defensive-transition": [
    "transicion defensiva",
    "tras perdida",
    "perdida",
    "repliegue",
    "rest defense",
    "contra tras perder",
    "perdemos la pelota",
    "perdemos",
    "tras perder",
  ],
  "offensive-transition": [
    "transicion ofensiva",
    "tras robo",
    "recuperacion y salida",
    "primer pase tras robo",
    "salida rapida",
  ],
  counter: [
    "contra",
    "contragolpe",
    "ataque rapido",
    "transicion rapida",
    "salida directa",
  ],
  "wide-areas": [
    "banda",
    "carril",
    "lateral",
    "costado",
    "zona exterior",
    "orientar afuera",
  ],
  "wide-defense": [
    "defensa de banda",
    "cerrar banda",
    "2v1 en banda",
    "lateral y extremo",
    "proteger el costado",
    "nos ganan por banda",
    "nos atacan por banda",
    "nos superan por fuera",
    "costado debil",
  ],
  "central-defense": [
    "defensa central",
    "por dentro",
    "carril central",
    "zona 14",
    "cerrar por dentro",
    "pase interior",
  ],
  crosses: [
    "centro",
    "centros",
    "segundo palo",
    "centro atras",
    "lateral al area",
  ],
  "set-pieces": [
    "abp",
    "pelota parada",
    "corner",
    "corners",
    "tiro libre",
    "saque de esquina",
  ],
  abp: [
    "abp",
    "pelota parada",
    "corner",
    "corners",
    "tiro libre",
    "saque de esquina",
  ],
  mark: [
    "marca",
    "marcar",
    "tomar hombre",
    "seguir referencia",
    "controlar referencia",
  ],
  "man-marking": [
    "marca hombre",
    "seguir al hombre",
    "persecucion individual",
    "mano a mano",
  ],
  zonal: [
    "zonal",
    "marca en zona",
    "cerrar zona",
    "defender zona",
  ],
  "man-oriented": [
    "orientado al hombre",
    "ajuste al hombre",
    "referencia individual",
  ],
  "second-ball": [
    "segunda pelota",
    "rebote",
    "segunda jugada",
    "caida del rebote",
  ],
  cover: [
    "cobertura",
    "cubrir espalda",
    "permuta defensiva",
    "tapar salida",
    "espalda del lateral",
    "espalda de centrales",
  ],
  "rest-defense": [
    "rest defense",
    "estructura de resguardo",
    "quedar equilibrados",
    "proteger contra",
  ],
};
