export {
  BOARD_SCHEMA_VERSION,
  BoardArrowEndpointSchema,
  BoardArrowSchema,
  BoardArrowSemanticSchema,
  BoardInstructionSchema,
  BoardInstructionScopeSchema,
  BoardLayerSchema,
  BoardObjectSchema,
  BoardObjectTypeSchema,
  BoardPhaseSchema,
  BoardPhaseTypeSchema,
  BoardPitchModeSchema,
  BoardPointSchema,
  BoardRosterLinkSchema,
  BoardSceneSchema,
  BoardStyleSchema,
  BoardVisibilitySchema,
  BoardZoneSchema,
  BoardZoneSemanticSchema,
  BoardZoneShapeSchema,
  TacticalBoardSchema,
  createBall,
  createBoardId,
  createDefaultBoard,
  createDefaultBoardScene,
  createInstruction,
  createOpponentShape,
  createOpponentToken,
  createPlayerToken,
  createSemanticArrow,
  createTacticalZone,
  duplicateBoardScene,
  generateBoardSessionDraft,
  reorderBoardScenes,
  summarizeBoard,
  summarizeBoardForAi,
  type BoardArrow,
  type BoardArrowEndpoint,
  type BoardArrowSemantic,
  type BoardInstruction,
  type BoardInstructionScope,
  type BoardLayer,
  type BoardObject,
  type BoardObjectType,
  type BoardPhase,
  type BoardPhaseType,
  type BoardPitchMode,
  type BoardPoint,
  type BoardRosterLink,
  type BoardScene,
  type BoardSessionDraft,
  type BoardStyle,
  type BoardVisibility,
  type BoardZone,
  type BoardZoneSemantic,
  type BoardZoneShape,
  type TacticalBoard,
} from "./boardModel";

export {
  buildBoardFilename,
  formatBoardExportDate,
  slugifyBoardFilenamePart,
  type BoardFilenameOptions,
} from "./filename";

export {
  BOARD_VIEWBOX_HEIGHT,
  BOARD_VIEWBOX_WIDTH,
  getBoardActorPositions,
  getBoardBallPosition,
  renderTacticalBoardSvgMarkup,
  type TacticalBoardSvgOptions,
} from "./renderBoardSvg";

export {
  buildBoardBriefingHtml,
  buildBoardSvgExport,
  buildExerciseBoardBriefingHtml,
  buildExerciseBoardSvgExport,
  buildTacticalBoardBriefingExport,
  tacticalBoardSceneSvgString,
  type BoardBriefingOptions,
  type TacticalBoardBriefAudience,
} from "./exportBoard";

export {
  buildBoardPayload,
  DEFAULT_BOARD_LAYERS,
  DEFAULT_EXERCISE_BUILDER,
  DEFAULT_TACTICAL_PROBLEM,
  inferAiInterpretation,
  type BoardAnnotation,
  type BoardPayload,
  type CurrentBoardView,
  type ExerciseBuilder,
  type PlanningBoardLayer,
  type PlanningBoardPlayer,
  type TacticalProblem,
} from "./productBoardTypes";
